######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 26 11:17:04 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += core gui
QT += widgets

# Input
SOURCES += main.cpp MainWindow.cpp NetworkWidget.cpp CameraWidget.cpp
