######################################################################
# Automatically generated by qmake (3.0) Thu Nov 5 21:13:34 2015
######################################################################

TEMPLATE = app
TARGET = PayloadGUI
INCLUDEPATH += .
QT += core gui
QT += widgets

QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += CameraWidget.h MainWindow.h NetworkWidget.h ImageViewer.h StarPacket0x01.h
SOURCES += CameraWidget.cpp main.cpp MainWindow.cpp NetworkWidget.cpp ImageViewer.cpp StarPacket0x01.cpp
